#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/freetest
##    url: jdbc:h2:~/freetest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#logging.level:
#  org.hibernate.SQL: debug
server:
  port: 8080
logging.level:
  org.hibernate.SQL: debug
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k5c101.p.ssafy.io:3306/csps?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  redis:
    port: 6379
    host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: yukariko7880@gmail.com
    password: sju71004007!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    credentials:
      accessKey: AKIA3BYAZ7LYYOEQ7OFC
      secretKey: 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
    s3:
      bucket: freepjt
    region:
      static: ap-northeast-2
    stack:
      auto: false
      
jwt:
  header: Authorization
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 6000
  refresh_expiration: 86400